# Generated by Django 4.2.8 on 2024-03-13 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KHO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ten', models.CharField(help_text='Ten cua Kho', max_length=255)),
                ('DiaChi', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MATHANG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ten', models.CharField(help_text='Ten cua mat hang', max_length=255)),
                ('MoTa', models.TextField()),
                ('DVT', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='KHOMATHANG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SoLuong', models.IntegerField(help_text='So luong cua mat hang')),
                ('Kho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qlkhohang.kho')),
                ('MatHang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qlkhohang.mathang')),
            ],
        ),
        migrations.AddField(
            model_name='kho',
            name='MatHang',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qlkhohang.mathang'),
        ),
    ]
