# Generated by Django 4.2.8 on 2024-03-13 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qlkhohang', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kho',
            name='MatHang',
        ),
        migrations.AlterField(
            model_name='mathang',
            name='DVT',
            field=models.CharField(choices=[('KG', 'kg'), ('CAI', 'kg'), ('CHAI', 'kg'), ('HOP', 'kg')], max_length=20),
        ),
        migrations.AddField(
            model_name='kho',
            name='MatHang',
            field=models.ManyToManyField(through='qlkhohang.KHOMATHANG', to='qlkhohang.mathang'),
        ),
    ]
