# Generated by Django 4.2.8 on 2024-04-04 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qlkhohang', '0002_remove_kho_mathang_alter_mathang_dvt_kho_mathang'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kho',
            name='DiaChi',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mathang',
            name='MoTa',
            field=models.TextField(null=True),
        ),
    ]
