# Generated by Django 4.2.8 on 2024-04-04 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qlkhohang', '0003_alter_kho_diachi_alter_mathang_mota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mathang',
            name='DVT',
            field=models.CharField(choices=[('KG', 'kg'), ('CAI', 'cai'), ('CHAI', 'chai'), ('HOP', 'hop')], max_length=20),
        ),
    ]
