# Generated by Django 4.2.8 on 2024-01-21 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the Project.', max_length=50)),
                ('description', models.CharField(help_text="The Project's description.", max_length=350)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the Task.', max_length=50)),
                ('description', models.CharField(help_text="The Task's description.", max_length=350)),
                ('due_date', models.DateField(verbose_name='Date the task was projected.')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectp.project')),
            ],
        ),
        migrations.CreateModel(
            name='TaskProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('RESPONSIBLE', 'Responsible'), ('CONTRIBUTOR', 'Contributor')], max_length=20, verbose_name='The role this project had in the task.')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectp.project')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectp.task')),
            ],
        ),
    ]
