# Generated by Django 4.2.8 on 2024-01-22 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TaskProject',
        ),
    ]
