# Generated by Django 4.2.8 on 2024-04-21 01:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DonVi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ten', models.CharField(max_length=255)),
                ('DiaChi', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LoaiThietBi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ten', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ThietBi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ten', models.CharField(max_length=255)),
                ('ThongSoKyThuat', models.TextField()),
                ('NgayBanGiao', models.DateField()),
                ('TinhTrang', models.CharField(choices=[('DangSuDung', 'Dangsudung'), ('HuHong', 'Huhong'), ('ThanhLy', 'Thanhly')], max_length=50)),
                ('DonViSuDung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qlthietbi.donvi')),
                ('LoaiThietBi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qlthietbi.loaithietbi')),
            ],
        ),
        migrations.AddField(
            model_name='loaithietbi',
            name='CacDonViSuDung',
            field=models.ManyToManyField(through='qlthietbi.ThietBi', to='qlthietbi.donvi'),
        ),
    ]
